/* tslint:disable */
/* eslint-disable */
/**
 * MultiversX Microservice API
 * ## Welcome the the MultiversX Microservice API!  Here you can set your custom documentation in markdown format 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PixelAvailableColorsBo
 */
export interface PixelAvailableColorsBo {
    /**
     * Hexadecimal color
     * @type {string}
     * @memberof PixelAvailableColorsBo
     */
    colorHex: string;
    /**
     * Discriminant on-chain
     * @type {number}
     * @memberof PixelAvailableColorsBo
     */
    discriminant: number;
}
