/* tslint:disable */
/* eslint-disable */
/**
 * MultiversX Microservice API
 * ## Welcome the the MultiversX Microservice API!  Here you can set your custom documentation in markdown format 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PixelInfosBo
 */
export interface PixelInfosBo {
    /**
     * x coordinate of the pixel
     * @type {number}
     * @memberof PixelInfosBo
     */
    x: number;
    /**
     * y coordinate of the pixel
     * @type {number}
     * @memberof PixelInfosBo
     */
    y: number;
    /**
     * Price the player has to pay to change the pixel's color
     * @type {string}
     * @memberof PixelInfosBo
     */
    priceToChange: string;
}
